### ISSUE TITLE
Fix the demo link

### ISSUE THREAD

**Issue by YakovL** [svgdotjs/svg.draw.js#14]
Hi, the link to the demo section in the README.md is broken, could you please fix it?

**Comment by Fuzzyma** [comment]
I moved the repo yesterday to the svgdotjs Organisation and didn't had the chance to fix that all. As a quick fix replace fuzzyma with svgdotjs in the link and it should work

**Comment by YakovL** [comment]
Well.. it does lead to an existing page (thanks), but that one also doesn't show any demo but points to http://fuzzyma.github.io/svg.draw.js/ as a page with demo. Is there any actual page with a demo now?

**Comment by Fuzzyma** [comment]
Well there is a link called "View Demo". When you click it you will get to this page: http://svgjs.com/svg.draw.js/demo/index.html

**Comment by YakovL** [comment]
Very cool, thanks a lot! May be this is a link to be added to the readme :)

**Comment by wout** [comment]
Soon we'll be adding examples of the plugins on the main page. So the one for this plugin will appear here: http://svgjs.com/plugins/svg-draw-js/

**Comment by YakovL** [comment]
Great, would be inspiring to see a freehand drawing and a constraint drawing there, too (if implemented)

[I'm looking for a framework to implement some drawing tools inside TiddlyWiki Classic, for now svg.js + svg.draw.js looks most promising; but, eh, looks like I'm starting to chit-chat in a wrong place, could you point some sort of community forum about svg.js? I don't see any such links at http://svgjs.com/]

**Comment by Fuzzyma** [comment]
Looks like anyone wants to program a drawing tool :D. svg.draw.js was created exactly because of that.
You might also take a look at svg.resize.js, svg.select.js and svg.draggable.js.
For the constraint thing: I saw the request but I dont see a way to make it work easily. Feel free to add it as a Pull Request if you want so.
We do not have a community forum or something right now. However iam following the stackoverflow svg.js tag. Also we might consider creating such a place for chit-chat

**Comment by Fuzzyma** [comment]
Fixed
