### ISSUE TITLE
cant draw a path using mouse

### ISSUE THREAD

**Issue by dani2819** [svgdotjs/svg.draw.js#23]
i want to do free hand drawing by using mouse like [this](https://bl.ocks.org/mbostock/f705fc55e6f26df29354). To do this i want to use svg **path** element. But, whenever i add this line:
`var draw = SVG('drawing').size(300, 300);`
`draw.path().stroke({color:'blue'}).draw();`

I get this error:
**Cannot read property point of undefined**

It looks that svg.draw.js hasn't any support to draw a path.

**Comment by Fuzzyma** [comment]
Correct. Drawing paths is not supported. Pull requests are always welcome!

**Comment by dani2819** [comment]
Can you suggest me any other way to do free hand drawing using svg.draw.js?

**Comment by Fuzzyma** [comment]
You could use lines instead.

**Comment by dani2819** [comment]
I tried to call this on mousemove function but it didnt worked as well:
`draw.polyline().fill('none').draw()`

**Comment by Fuzzyma** [comment]
On the Readme file you can see how to draw E. G. A new point of a polyline

**Comment by 1kohei1** [comment]
Hi,
I came to the same problem and this is how I solved. https://codepen.io/1kohei1/pen/xLvPpq

I didn't want to draw a circle for each plot, so I extended the line, polyline, and polygon without drawCircle function. Also, since I didn't find CDN for SVG.draw.js, pasted minified version of svg.draw.js. 

Hope it helps!

**Comment by Fuzzyma** [comment]
@1kohei1 I reviewed your code but couldn't find anything related to paths.

If all you want is removing the extra circles search the issues. There is another way easier way to do this by just overwriting the circle function with a noop.

For the CDN you can always go for rawgithub.com which is exactly for this use case

PS: #11

**Comment by 1kohei1** [comment]
Your comment addressed how to plot new point in the polyline. But I was not sure about the actual implementation. So I wanted to share how to draw a line (or path) with mouse move with actual code.

**Comment by Fuzzyma** [comment]
Ah okay thanks!

**Comment by Shubhambj** [comment]
Hi,
I came to the same problem and this is how I solved. https://codepen.io/1kohei1/pen/xLvPpq

I didn't want to draw a circle for each plot, so I extended the line, polyline, and polygon without drawCircle function. Also, since I didn't find CDN for SVG.draw.js, pasted minified version of svg.draw.js.

Hope it helps!

@1kohei1 it really help bro thanks
