### ISSUE TITLE
Draw multiple times, "drawdone" only fires once.

### ISSUE THREAD

**Issue by sefaYavuz** [svgdotjs/svg.draw.js#28]
I want to draw multiple times (not just once, like in the demo's). How can i do this? I have the following code:

```
var gridSize = 20;
var svg = new SVG('container').size('100%', '100%');
var polygon = createPolygon();

polygon.on('drawstart', function(e){
	document.addEventListener('keydown', function(e){
		if(e.keyCode == 13){
			polygon.draw('done');
			polygon = createPolygon();
		}
	});
});

function createPolygon() {
	var polygon = svg.polygon();
   	polygon.attr({
		'stroke-width': 1,
		'fill': 'none'
	})
	polygon.draw({snapToGrid: gridSize});

	return polygon;
};
```
I can draw multiple polygons with this code. But the `drawdone` event only fires the first time after calling `polygon.draw('done')`. Is it possible to make it fire off everytime when the method is called?

**Comment by Fuzzyma** [comment]
It fires every time but I guess, that you bind ONCE to this event with `polygon.on('drawdone', fb)`. But when you overwrite the variable `polygon` with your new polygon, the event handler does not magically jump to the new value of teh variable. You have to bind it again - its a new element. The event handler is not bound to a variablename. Its bound to an actual element. You only bind to the very first and never again.

Note that I only assume that this is the case because the crucial code for this part is missing
